In [51]:
# Dependencies
import requests
import numpy as np
import pandas as pd
from census import Census
import matplotlib.pyplot as plt

In [63]:
api_key = "a63d5bb264baf41c8c8d35a42353fe800f86bb99"
year = 2021
# Create an instance of the Census library
c = Census(
    api_key,
    year = year
)

# "B01003_001E": "Population",
# "B01002_001E": "Median Age",
# "B19013_001E": "Household Income",
# "B19301_001E": "Per Capita Income",
# "B17001_002E": "Poverty Count",
# "B15003_022E" : Education_bachelors,
# "B25077_001E" : Median_home_value

In [64]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
census_data = c.acs5.get(
    (
        "NAME",
        "B19013_001E",
        "B01003_001E",
        "B01002_001E",
        "B19301_001E",
        "B17001_002E",
        "B15003_022E",
        "B25077_001E"
    ),
    {'for': 'zip code tabulation area:*'}
)

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column renaming
census_pd = census_pd.rename(
    columns = {
        "B01003_001E": "Population",
        "B01002_001E": "Median Age",
        "B19013_001E": "Household Income",
        "B19301_001E": "Per Capita Income",
        "B17001_002E": "Poverty Count",
        "B15003_022E" : "Education_bachelors",
        "B25077_001E" : "Median_home_value",
        "NAME": "Name",
        "zip code tabulation area": "Zipcode"
    }
)

# Add a Poverty Rate column (Poverty Count / Population)
census_pd["Poverty Rate"] = 100 * census_pd["Poverty Count"].astype(int) / census_pd["Population"].astype(int)

In [65]:
# Configure the final DataFrame
census_pd = census_pd[
    [
        "Zipcode",
        "Population",
        "Median Age",
        "Household Income",
        "Per Capita Income",
        "Poverty Count",
        "Poverty Rate",
        "Education_bachelors",
        "Median_home_value"
    ]
]

census_pd["Year"]=year
# Display DataFrame length and sample data
print(f"Number of rows in the DataFrame: {len(census_pd)}")
census_pd.head()

Number of rows in the DataFrame: 33774

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Education_bachelors,Median_home_value,Year
0,00601,17126.0,43.7,15292.0,7587.0,11302.0,65.993227,1592.0,78800.0,2021
1,00602,37895.0,44.4,18716.0,10699.0,17121.0,45.180103,4659.0,88500.0,2021
2,00603,49136.0,44.1,16789.0,12280.0,23617.0,48.064556,6042.0,121600.0,2021
3,00606,5751.0,44.9,18835.0,8574.0,3139.0,54.581812,313.0,96500.0,2021
4,00610,26153.0,43.5,21239.0,11638.0,11640.0,44.507322,2769.0,89900.0,2021

In [66]:
# Save the DataFrame as a CSV
# Note: To avoid any issues later, use encoding="utf-8"
census_pd.to_csv("census_data_2021.csv", encoding="utf-8", index=False)